// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TermometroAereo

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_AliDiClasseLogo;
lv_obj_t * ui_InfoLabel;
lv_obj_t * ui_VersionLabel;
lv_obj_t * ui_CreditsLabel;
lv_obj_t * ui_BernaLogo;

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
void ui_event_SettingBtn(lv_event_t * e);
lv_obj_t * ui_SettingBtn;
lv_obj_t * ui_SettingIcon;
void ui_event_PressureHumidityBtn(lv_event_t * e);
lv_obj_t * ui_PressureHumidityBtn;
void ui_event_ResetRuntimeBtn(lv_event_t * e);
lv_obj_t * ui_ResetRuntimeBtn;
lv_obj_t * ui_ModelLabel;
lv_obj_t * ui_RegistrationLabel;
lv_obj_t * ui_TimeHS;
lv_obj_t * ui_DateTimeLabel;
lv_obj_t * ui_DateText;
lv_obj_t * ui_HourText;
lv_obj_t * ui_TemperaturesHS;
lv_obj_t * ui_TemperaturesLabel;
lv_obj_t * ui_InTempLabel;
lv_obj_t * ui_InTempText;
lv_obj_t * ui_OutTempLabel;
lv_obj_t * ui_OutTempText;
lv_obj_t * ui_PressureLabel;
lv_obj_t * ui_PressureText;
lv_obj_t * ui_RunTimeHS;
lv_obj_t * ui_RuntimeLabel;
lv_obj_t * ui_RuntimeText;

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t * ui_Settings;
lv_obj_t * ui_BacklightLabel;
lv_obj_t * ui_BrightnessLessIcon;
lv_obj_t * ui_BrightnessMoreIcon;
void ui_event_BacklightSlider(lv_event_t * e);
lv_obj_t * ui_BacklightSlider;
void ui_event_BackMainBtn(lv_event_t * e);
lv_obj_t * ui_BackMainBtn;
lv_obj_t * ui_BackMainBtnLabel;
lv_obj_t * ui_FuelTankChangeAlertLabel;
void ui_event_FuelTankChangeAlertDropdown(lv_event_t * e);
lv_obj_t * ui_FuelTankChangeAlertDropdown;
lv_obj_t * ui_ShowRunTimeSeconds;
void ui_event_ShowRunTimeSecondsSwitch(lv_event_t * e);
lv_obj_t * ui_ShowRunTimeSecondsSwitch;
lv_obj_t * ui_AdjustClockLabel;
void ui_event_DayDropdown(lv_event_t * e);
lv_obj_t * ui_DayDropdown;
void ui_event_MonthDropdown(lv_event_t * e);
lv_obj_t * ui_MonthDropdown;
void ui_event_YearDropdown(lv_event_t * e);
lv_obj_t * ui_YearDropdown;
void ui_event_HourDropdown(lv_event_t * e);
lv_obj_t * ui_HourDropdown;
void ui_event_MinuteDropdown(lv_event_t * e);
lv_obj_t * ui_MinuteDropdown;
void ui_event_SaveClockBtn(lv_event_t * e);
lv_obj_t * ui_SaveClockBtn;
lv_obj_t * ui_SaveclockBtnLabel;

// SCREEN: ui_AdvancedSettings
void ui_AdvancedSettings_screen_init(void);
lv_obj_t * ui_AdvancedSettings;
lv_obj_t * ui_AdvancedSettingsLabel;
lv_obj_t * ui_AdjustInsideTempLabel;
void ui_event_AdjustInsideTempDropdown(lv_event_t * e);
lv_obj_t * ui_AdjustInsideTempDropdown;
lv_obj_t * ui_AdjustOutsideTempLabel;
void ui_event_AdjustOutsideTempDropdown(lv_event_t * e);
lv_obj_t * ui_AdjustOutsideTempDropdown;
void ui_event_BackSettingsBtn(lv_event_t * e);
lv_obj_t * ui_BackSettingsBtn;
lv_obj_t * ui_BackSettingsBtnLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SettingBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(ui_AdvancedSettings, LV_SCR_LOAD_ANIM_NONE, 500, 0);
    }
}
void ui_event_PressureHumidityBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        TogglePressureHumidity(e);
    }
}
void ui_event_ResetRuntimeBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ResetRuntime(e);
    }
}
void ui_event_BacklightSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateDisplayBacklight(e);
    }
}
void ui_event_BackMainBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}
void ui_event_FuelTankChangeAlertDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FuelTankAlertValueChange(e);
    }
}
void ui_event_ShowRunTimeSecondsSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ToggleShowRuntimeSeconds(e);
    }
}
void ui_event_DayDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AdjustRtcIsValid(e);
    }
}
void ui_event_MonthDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AdjustRtcIsValid(e);
    }
}
void ui_event_YearDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AdjustRtcIsValid(e);
    }
}
void ui_event_HourDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AdjustRtcIsValid(e);
    }
}
void ui_event_MinuteDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AdjustRtcIsValid(e);
    }
}
void ui_event_SaveClockBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        AdjustRtc(e);
    }
}
void ui_event_AdjustInsideTempDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AdjustIntTempValueChange(e);
    }
}
void ui_event_AdjustOutsideTempDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AdjustExtTempValueChange(e);
    }
}
void ui_event_BackSettingsBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_Main_screen_init();
    ui_Settings_screen_init();
    ui_AdvancedSettings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
