// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TermometroAereo

#ifndef _TERMOMETROAEREO_UI_H
#define _TERMOMETROAEREO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_AliDiClasseLogo;
extern lv_obj_t * ui_InfoLabel;
extern lv_obj_t * ui_VersionLabel;
extern lv_obj_t * ui_CreditsLabel;
extern lv_obj_t * ui_BernaLogo;
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
void ui_event_SettingBtn(lv_event_t * e);
extern lv_obj_t * ui_SettingBtn;
extern lv_obj_t * ui_SettingIcon;
void ui_event_PressureHumidityBtn(lv_event_t * e);
extern lv_obj_t * ui_PressureHumidityBtn;
void ui_event_ResetRuntimeBtn(lv_event_t * e);
extern lv_obj_t * ui_ResetRuntimeBtn;
extern lv_obj_t * ui_ModelLabel;
extern lv_obj_t * ui_RegistrationLabel;
extern lv_obj_t * ui_TimeHS;
extern lv_obj_t * ui_DateTimeLabel;
extern lv_obj_t * ui_DateText;
extern lv_obj_t * ui_HourText;
extern lv_obj_t * ui_TemperaturesHS;
extern lv_obj_t * ui_TemperaturesLabel;
extern lv_obj_t * ui_InTempLabel;
extern lv_obj_t * ui_InTempText;
extern lv_obj_t * ui_OutTempLabel;
extern lv_obj_t * ui_OutTempText;
extern lv_obj_t * ui_PressureLabel;
extern lv_obj_t * ui_PressureText;
extern lv_obj_t * ui_RunTimeHS;
extern lv_obj_t * ui_RuntimeLabel;
extern lv_obj_t * ui_RuntimeText;
// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_BacklightLabel;
extern lv_obj_t * ui_BrightnessLessIcon;
extern lv_obj_t * ui_BrightnessMoreIcon;
void ui_event_BacklightSlider(lv_event_t * e);
extern lv_obj_t * ui_BacklightSlider;
void ui_event_BackMainBtn(lv_event_t * e);
extern lv_obj_t * ui_BackMainBtn;
extern lv_obj_t * ui_BackMainBtnLabel;
extern lv_obj_t * ui_FuelTankChangeAlertLabel;
void ui_event_FuelTankChangeAlertDropdown(lv_event_t * e);
extern lv_obj_t * ui_FuelTankChangeAlertDropdown;
extern lv_obj_t * ui_ShowRunTimeSeconds;
void ui_event_ShowRunTimeSecondsSwitch(lv_event_t * e);
extern lv_obj_t * ui_ShowRunTimeSecondsSwitch;
extern lv_obj_t * ui_AdjustClockLabel;
void ui_event_DayDropdown(lv_event_t * e);
extern lv_obj_t * ui_DayDropdown;
void ui_event_MonthDropdown(lv_event_t * e);
extern lv_obj_t * ui_MonthDropdown;
void ui_event_YearDropdown(lv_event_t * e);
extern lv_obj_t * ui_YearDropdown;
void ui_event_HourDropdown(lv_event_t * e);
extern lv_obj_t * ui_HourDropdown;
void ui_event_MinuteDropdown(lv_event_t * e);
extern lv_obj_t * ui_MinuteDropdown;
void ui_event_SaveClockBtn(lv_event_t * e);
extern lv_obj_t * ui_SaveClockBtn;
extern lv_obj_t * ui_SaveclockBtnLabel;
// SCREEN: ui_AdvancedSettings
void ui_AdvancedSettings_screen_init(void);
extern lv_obj_t * ui_AdvancedSettings;
extern lv_obj_t * ui_AdvancedSettingsLabel;
extern lv_obj_t * ui_AdjustInsideTempLabel;
void ui_event_AdjustInsideTempDropdown(lv_event_t * e);
extern lv_obj_t * ui_AdjustInsideTempDropdown;
extern lv_obj_t * ui_AdjustOutsideTempLabel;
void ui_event_AdjustOutsideTempDropdown(lv_event_t * e);
extern lv_obj_t * ui_AdjustOutsideTempDropdown;
void ui_event_BackSettingsBtn(lv_event_t * e);
extern lv_obj_t * ui_BackSettingsBtn;
extern lv_obj_t * ui_BackSettingsBtnLabel;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_adc_logo_png);    // assets\ADC_logo.png
LV_IMG_DECLARE(ui_img_berna_logo_png);    // assets\berna_logo.png
LV_IMG_DECLARE(ui_img_settings_icon_png);    // assets\settings_icon.png
LV_IMG_DECLARE(ui_img_brightness_less_icon_png);    // assets\brightness_less_icon.png
LV_IMG_DECLARE(ui_img_brightness_more_icon_png);    // assets\brightness_more_icon.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
