// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TermometroAereo

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void TogglePressureHumidity(lv_event_t * e);
void ResetRuntime(lv_event_t * e);
void updateDisplayBacklight(lv_event_t * e);
void FuelTankAlertValueChange(lv_event_t * e);
void ToggleShowRuntimeSeconds(lv_event_t * e);
void AdjustRtcIsValid(lv_event_t * e);
void AdjustRtcIsValid(lv_event_t * e);
void AdjustRtcIsValid(lv_event_t * e);
void AdjustRtcIsValid(lv_event_t * e);
void AdjustRtcIsValid(lv_event_t * e);
void AdjustRtc(lv_event_t * e);
void AdjustIntTempValueChange(lv_event_t * e);
void AdjustExtTempValueChange(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
