// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: TermometroAereo

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BacklightLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_BacklightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BacklightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BacklightLabel, 0);
    lv_obj_set_y(ui_BacklightLabel, 10);
    lv_obj_set_align(ui_BacklightLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_BacklightLabel, "Backlight");

    ui_BrightnessLessIcon = lv_img_create(ui_Settings);
    lv_img_set_src(ui_BrightnessLessIcon, &ui_img_brightness_less_icon_png);
    lv_obj_set_width(ui_BrightnessLessIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessLessIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessLessIcon, 5);
    lv_obj_set_y(ui_BrightnessLessIcon, 37);
    lv_obj_add_flag(ui_BrightnessLessIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessLessIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessMoreIcon = lv_img_create(ui_Settings);
    lv_img_set_src(ui_BrightnessMoreIcon, &ui_img_brightness_more_icon_png);
    lv_obj_set_width(ui_BrightnessMoreIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessMoreIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessMoreIcon, -5);
    lv_obj_set_y(ui_BrightnessMoreIcon, 37);
    lv_obj_set_align(ui_BrightnessMoreIcon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BrightnessMoreIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessMoreIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BacklightSlider = lv_slider_create(ui_Settings);
    lv_slider_set_range(ui_BacklightSlider, 5, 254);
    lv_slider_set_value(ui_BacklightSlider, 254, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BacklightSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BacklightSlider, 5,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_BacklightSlider, 160);
    lv_obj_set_height(ui_BacklightSlider, 12);
    lv_obj_set_x(ui_BacklightSlider, 0);
    lv_obj_set_y(ui_BacklightSlider, 40);
    lv_obj_set_align(ui_BacklightSlider, LV_ALIGN_TOP_MID);

    ui_BackMainBtn = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_BackMainBtn, 110);
    lv_obj_set_height(ui_BackMainBtn, 50);
    lv_obj_set_x(ui_BackMainBtn, -5);
    lv_obj_set_y(ui_BackMainBtn, -10);
    lv_obj_set_align(ui_BackMainBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BackMainBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackMainBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackMainBtn, lv_color_hex(0xFA8500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackMainBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackMainBtnLabel = lv_label_create(ui_BackMainBtn);
    lv_obj_set_width(ui_BackMainBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackMainBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackMainBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackMainBtnLabel, "Back");

    ui_FuelTankChangeAlertLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_FuelTankChangeAlertLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuelTankChangeAlertLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuelTankChangeAlertLabel, 5);
    lv_obj_set_y(ui_FuelTankChangeAlertLabel, 78);
    lv_label_set_text(ui_FuelTankChangeAlertLabel, "Fuel tank change\nalert every (min)");

    ui_FuelTankChangeAlertDropdown = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_FuelTankChangeAlertDropdown,
                            "Off\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59\n60");
    lv_obj_set_width(ui_FuelTankChangeAlertDropdown, 60);
    lv_obj_set_height(ui_FuelTankChangeAlertDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuelTankChangeAlertDropdown, -5);
    lv_obj_set_y(ui_FuelTankChangeAlertDropdown, 77);
    lv_obj_set_align(ui_FuelTankChangeAlertDropdown, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_FuelTankChangeAlertDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ShowRunTimeSeconds = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_ShowRunTimeSeconds, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShowRunTimeSeconds, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShowRunTimeSeconds, 5);
    lv_obj_set_y(ui_ShowRunTimeSeconds, 124);
    lv_label_set_text(ui_ShowRunTimeSeconds, "Show run time seconds");

    ui_ShowRunTimeSecondsSwitch = lv_switch_create(ui_Settings);
    lv_obj_set_width(ui_ShowRunTimeSecondsSwitch, 50);
    lv_obj_set_height(ui_ShowRunTimeSecondsSwitch, 25);
    lv_obj_set_x(ui_ShowRunTimeSecondsSwitch, -5);
    lv_obj_set_y(ui_ShowRunTimeSecondsSwitch, 120);
    lv_obj_set_align(ui_ShowRunTimeSecondsSwitch, LV_ALIGN_TOP_RIGHT);

    ui_AdjustClockLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_AdjustClockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AdjustClockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AdjustClockLabel, 0);
    lv_obj_set_y(ui_AdjustClockLabel, 155);
    lv_obj_set_align(ui_AdjustClockLabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_AdjustClockLabel, "Adjust Clock (UTC)");

    ui_DayDropdown = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_DayDropdown,
                            "Day\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31");
    lv_obj_set_width(ui_DayDropdown, 67);
    lv_obj_set_height(ui_DayDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayDropdown, 5);
    lv_obj_set_y(ui_DayDropdown, 35);
    lv_obj_set_align(ui_DayDropdown, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DayDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MonthDropdown = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_MonthDropdown, "Month\n1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12");
    lv_obj_set_width(ui_MonthDropdown, 85);
    lv_obj_set_height(ui_MonthDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MonthDropdown, -2);
    lv_obj_set_y(ui_MonthDropdown, 35);
    lv_obj_set_align(ui_MonthDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MonthDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_YearDropdown = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_YearDropdown,
                            "Year\n2020\n2021\n2022\n2023\n2024\n2025\n2026\n2027\n2028\n2029\n2030\n2031\n2032\n2033\n2034\n2035\n2036\n2037\n2038\n2039\n2040\n2041\n2042\n2043\n2044\n2045\n2046\n2047\n2048\n2049\n2050\n2051\n2052\n2053\n2054\n2055\n2056\n2057\n2058\n2059\n2060\n2061\n2062\n2063\n2064\n2065\n2066\n2067\n2068\n2069\n2070\n2071\n2072\n2073\n2074\n2075\n2076\n2077\n2078\n2079\n2080\n2081\n2082\n2083\n2084\n2085\n2086\n2087\n2088\n2089\n2090\n2091\n2092\n2093\n2094\n2095\n2096\n2097\n2098\n2099\n2100");
    lv_obj_set_width(ui_YearDropdown, 70);
    lv_obj_set_height(ui_YearDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_YearDropdown, -5);
    lv_obj_set_y(ui_YearDropdown, 35);
    lv_obj_set_align(ui_YearDropdown, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_YearDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_HourDropdown = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_HourDropdown,
                            "Hour\n00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23");
    lv_obj_set_width(ui_HourDropdown, 112);
    lv_obj_set_height(ui_HourDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourDropdown, 5);
    lv_obj_set_y(ui_HourDropdown, 75);
    lv_obj_set_align(ui_HourDropdown, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_HourDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MinuteDropdown = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_MinuteDropdown,
                            "Minute\n00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59");
    lv_obj_set_width(ui_MinuteDropdown, 112);
    lv_obj_set_height(ui_MinuteDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteDropdown, -5);
    lv_obj_set_y(ui_MinuteDropdown, 75);
    lv_obj_set_align(ui_MinuteDropdown, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_MinuteDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SaveClockBtn = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_SaveClockBtn, 110);
    lv_obj_set_height(ui_SaveClockBtn, 50);
    lv_obj_set_x(ui_SaveClockBtn, 5);
    lv_obj_set_y(ui_SaveClockBtn, -10);
    lv_obj_set_align(ui_SaveClockBtn, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_state(ui_SaveClockBtn, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_SaveClockBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveClockBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SaveclockBtnLabel = lv_label_create(ui_SaveClockBtn);
    lv_obj_set_width(ui_SaveclockBtnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveclockBtnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SaveclockBtnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveclockBtnLabel, "Save");

    lv_obj_add_event_cb(ui_BacklightSlider, ui_event_BacklightSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackMainBtn, ui_event_BackMainBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FuelTankChangeAlertDropdown, ui_event_FuelTankChangeAlertDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ShowRunTimeSecondsSwitch, ui_event_ShowRunTimeSecondsSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DayDropdown, ui_event_DayDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MonthDropdown, ui_event_MonthDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_YearDropdown, ui_event_YearDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HourDropdown, ui_event_HourDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MinuteDropdown, ui_event_MinuteDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveClockBtn, ui_event_SaveClockBtn, LV_EVENT_ALL, NULL);

}
